### PR TITLE
Remove cycle

### PR DESCRIPTION
**Pull request by dominik1001**
Hi @zoellner ! It'd be great if you could accept this PR. I removed an unnecessary dependency that is causing license issues. We're also willing to take over the maintenance of this library.
Thank you,
Dominik

### CODE REVIEW

**Review by zoellner — APPROVED** [review]

**Comment by zoellner** [comment]
Just merged this and published as 3.2.1

**Comment by zoellner** [comment]
Happy to transfer the repo and associated npm package to you/chatchamp

**Comment by dominik1001** [comment]
@zoellner Awesome! Thank you! 👍 
Feel free to transfer both to `chatchamp` and we will take care of maintenance.

**Comment by dominik1001** [comment]
@zoellner I just noticed that somehow the changes didn't make it to published version 3.2.1

**Comment by zoellner** [comment]
my bad. fixed that in 3.2.2

**Pull request merged**
